[project]
name = "mcp-agent"
version = "0.0.7"
description = "Build effective agents with Model Context Protocol (MCP) using simple, composable patterns."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Sarmad Qadri", email = "sarmad@lastmileai.dev" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent"
]
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.6",
    "instructor>=1.7.0",
    "mcp>=1.2.1",
    "opentelemetry-distro>=0.50b0",
    "opentelemetry-exporter-otlp-proto-http>=1.29.0",
    "pydantic-settings>=2.7.0",
    "pydantic>=2.10.4",
    "pyyaml>=6.0.2",
    "rich>=13.9.4",
    "typer>=0.15.1",
    "numpy>=2.2.1",
    "scikit-learn>=1.6.0",
]

[project.optional-dependencies]
temporal = [
    "temporalio>=1.8.0",
]
anthropic = [
    "anthropic>=0.42.0",
    "instructor[anthropic]>=1.7.2",
]
openai = [
    "openai>=1.58.1",
]
cohere = [
    "cohere>=5.13.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "anthropic>=0.42.0",
    "pre-commit>=4.0.1",
    "pydantic>=2.10.4",
    "pyyaml>=6.0.2",
    "ruff>=0.8.4",
    "tomli>=2.2.1",
]

[project.scripts]
mcp-agent = "mcp_agent.cli.__main__:app"
mcp_agent = "mcp_agent.cli.__main__:app"
mcpagent = "mcp_agent.cli.__main__:app"
silsila = "mcp_agent.cli.__main__:app"

[tool.setuptools.packages.find]
include = ["mcp-agent"]

[tool.setuptools.package-data]
mcp-agent = ["data/*.json"]

[tool.uv.workspace]
members = ["examples/streamlit_mcp_basic_agent"]
