[project]
name = "fast-agent-mcp"
version = "0.0.7"
description = "Build, Test, Deploy composable MCP Agent Workflows."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Shaun Smith", email = "fastagent@llmindset.co.uk"},
    { name = "Sarmad Qadri", email = "sarmad@lastmileai.dev" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent"
]
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.6",
    "instructor>=1.7.2",
    "mcp==1.2.1",
    "opentelemetry-distro>=0.50b0",
    "opentelemetry-exporter-otlp-proto-http>=1.29.0",
    "pydantic-settings>=2.7.0",
    "pydantic>=2.10.4",
    "pyyaml>=6.0.2",
    "rich>=13.9.4",
    "typer>=0.15.1",
    "numpy>=2.2.1",
    "scikit-learn>=1.6.0",
    "pyreadline3>=3.5.4",
    "anthropic>=0.42.0",
    "openai>=1.63.2",
]

[project.optional-dependencies]
temporal = [
    "temporalio>=1.8.0",
]
anthropic = [
    "anthropic>=0.42.0",
    "instructor[anthropic]>=1.7.2",
]
openai = [
    "openai>=1.58.1",
]
cohere = [
    "cohere>=5.13.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mcp_agent"]

[tool.hatch.build]
include = [
    "src/mcp_agent/**/*.py",
    "src/mcp_agent/resources/**/*.py",
]

[dependency-groups]
dev = [
    "anthropic>=0.42.0",
    "pre-commit>=4.0.1",
    "pydantic>=2.10.4",
    "pyyaml>=6.0.2",
    "ruff>=0.8.4",
    "tomli>=2.2.1",
]

[project.scripts]
fast-agent = "mcp_agent.cli.__main__:app"
fast_agent = "mcp_agent.cli.__main__:app"
fastagent = "mcp_agent.cli.__main__:app"
silsila = "mcp_agent.cli.__main__:app"

[tool.setuptools.package-data]
mcp-agent = ["data/*.json"]
mcp_agent = ["resources/examples/**/*.py"]  # Include all Python files in examples subdirectories

