$schema: ../../schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  type: file
  level: debug
  path: "router.jsonl"

mcp:
  servers:
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
    filesystem:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem"]

openai:
  # Secrets (API keys, etc.) are stored in an mcp_agent.secrets.yaml file which can be gitignored
  default_model: "gpt-4o-mini"
