$schema: ../../schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  type: console
  level: error
  path: "./mcp_agent.log"

mcp:
  servers:
    mcp_root:
      type: "mcp_root"
      command: "uv"
      args: ["run", "../mcp_root_test/root_test_server.py"]

openai:
  # Secrets (API keys, etc.) are stored in an mcp_agent.secrets.yaml file
  default_model: o3-mini
  reasoning_effort: low
